In [2]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline

In [82]:
df = pd.read_csv("test100.csv")
df.head()

,subject_id,hadm_id,long_title,starttime,endtime,amount,admittime,dischtime,deathtime,deathflag
0,188,192557,06-Insulin (Non IV),11/26/2160 1:34,11/26/2160 1:35,4,11/25/2160 21:55,11/28/2160 12:42,NaN,0
1,188,192557,06-Insulin (Non IV),11/26/2160 6:02,11/26/2160 6:03,2,11/25/2160 21:55,11/28/2160 12:42,NaN,0
2,188,192557,06-Insulin (Non IV),11/26/2160 9:30,11/26/2160 9:31,30,11/25/2160 21:55,11/28/2160 12:42,NaN,0
3,188,192557,06-Insulin (Non IV),11/26/2160 12:49,11/26/2160 12:50,4,11/25/2160 21:55,11/28/2160 12:42,NaN,0
4,188,192557,06-Insulin (Non IV),11/26/2160 18:00,11/26/2160 18:01,8,11/25/2160 21:55,11/28/2160 12:42,NaN,0

In [83]:
df = df.sort_values(by=['subject_id','hadm_id','starttime'],ascending=[True, True, False])
df = df.reset_index(drop=True)
df.head()

,subject_id,hadm_id,long_title,starttime,endtime,amount,admittime,dischtime,deathtime,deathflag
0,188,123860,06-Insulin (Non IV),1/3/2161 10:17,1/3/2161 10:18,5,12/31/2160 12:34,1/8/2161 19:50,NaN,0
1,188,123860,06-Insulin (Non IV),1/3/2161 10:17,1/3/2161 10:18,30,12/31/2160 12:34,1/8/2161 19:50,NaN,0
2,188,123860,06-Insulin (Non IV),1/2/2161 22:22,1/2/2161 22:23,0,12/31/2160 12:34,1/8/2161 19:50,NaN,0
3,188,123860,06-Insulin (Non IV),1/2/2161 22:22,1/2/2161 22:23,30,12/31/2160 12:34,1/8/2161 19:50,NaN,0
4,188,123860,06-Insulin (Non IV),1/2/2161 18:15,1/2/2161 18:16,7,12/31/2160 12:34,1/8/2161 19:50,NaN,0

In [86]:
# add a column with a one row look ahead on hadm_id
hadm_id_next = pd.concat([df['hadm_id'][1:], pd.Series([None])])
hadm_id_next = hadm_id_next.reset_index(drop=True)
hadm_id_next.name = 'hadm_id_next'

# add a column with row look ahead on subject_id
subject_id_next = pd.concat([df['subject_id'][1:], pd.Series([None])])
subject_id_next = subject_id_next.reset_index(drop=True)
subject_id_next.name = 'subject_id_next'
subject_id_next.head()

0    188
1    188
2    188
3    188
4    188
Name: subject_id_next, dtype: object

In [87]:
df = pd.concat([df, hadm_id_next, subject_id_next], axis=1)
df

,subject_id,hadm_id,long_title,starttime,endtime,amount,admittime,dischtime,deathtime,deathflag,hadm_id_next,subject_id_next
0,188,123860,06-Insulin (Non IV),1/3/2161 10:17,1/3/2161 10:18,5,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
1,188,123860,06-Insulin (Non IV),1/3/2161 10:17,1/3/2161 10:18,30,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
2,188,123860,06-Insulin (Non IV),1/2/2161 22:22,1/2/2161 22:23,0,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
3,188,123860,06-Insulin (Non IV),1/2/2161 22:22,1/2/2161 22:23,30,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
4,188,123860,06-Insulin (Non IV),1/2/2161 18:15,1/2/2161 18:16,7,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
5,188,123860,06-Insulin (Non IV),1/2/2161 16:30,1/2/2161 16:31,7,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
6,188,123860,06-Insulin (Non IV),1/2/2161 14:17,1/2/2161 14:18,7,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
7,188,123860,06-Insulin (Non IV),1/2/2161 11:00,1/2/2161 11:01,5,12/31/2160 12:34,1/8/2161 19:50,NaN,0,123860,188
8,188,123860,06-Insulin (Non IV),1/2/2161 11:00,1/2/2161 11:01,30,12/31/2160 12:34,1/8/2161 19:50,NaN,0,132401,188
9,188,132401,06-Insulin (Non IV),12/17/2161 4:00,12/17/2161 4:01,7,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
10,188,132401,06-Insulin (Non IV),12/17/2161 15:00,12/17/2161 15:01,19,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
11,188,132401,06-Insulin (Non IV),12/17/2161 10:00,12/17/2161 10:01,19,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
12,188,132401,06-Insulin (Non IV),12/17/2161 10:00,12/17/2161 10:01,55,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
13,188,132401,06-Insulin (Non IV),12/16/2161 4:27,12/16/2161 4:28,7,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
14,188,132401,06-Insulin (Non IV),12/16/2161 22:00,12/16/2161 22:01,8,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
15,188,132401,06-Insulin (Non IV),12/16/2161 22:00,12/16/2161 22:01,55,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
16,188,132401,06-Insulin (Non IV),12/16/2161 17:30,12/16/2161 17:31,9,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
17,188,132401,06-Insulin (Non IV),12/16/2161 14:40,12/16/2161 14:41,9,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
18,188,132401,06-Insulin (Non IV),12/16/2161 11:00,12/16/2161 11:01,55,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
19,188,132401,06-Insulin (Non IV),12/16/2161 10:59,12/16/2161 11:00,5,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
20,188,132401,06-Insulin (Non IV),12/15/2161 4:07,12/15/2161 4:08,3,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
21,188,132401,06-Insulin (Non IV),12/15/2161 22:19,12/15/2161 22:20,4,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
22,188,132401,06-Insulin (Non IV),12/15/2161 22:18,12/15/2161 22:19,50,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
23,188,132401,06-Insulin (Non IV),12/15/2161 18:26,12/15/2161 18:27,3,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
24,188,132401,06-Insulin (Non IV),12/14/2161 22:32,12/14/2161 22:33,55,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
25,188,132401,06-Insulin (Non IV),12/14/2161 10:14,12/14/2161 10:15,3,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
26,188,132401,06-Insulin (Non IV),1/13/2162 10:42,1/13/2162 10:43,30,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,132401,188
27,188,132401,06-Insulin (Non IV),1/13/2162 10:41,1/13/2162 10:42,6,11/1/2161 17:48,1/17/2162 5:50,1/17/2162 5:50,1,164735,188
28,188,164735,06-Insulin (Non IV),7/6/2161 0:24,7/6/2161 0:25,4,7/1/2161 19:44,7/10/2161 20:00,NaN,0,164735,188
29,188,164735,06-Insulin (Non IV),7/5/2161 6:07,7/5/2161 6:08,6,7/1/2161 19:44,7/10/2161 20:00,NaN,0,164735,188
...,...,...,...,...,...,...,...,...,...,...,...,...
70,305,194340,06-Insulin (Non IV),9/5/2129 10:14,9/5/2129 10:15,9,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
71,305,194340,06-Insulin (Non IV),9/4/2129 5:00,9/4/2129 5:01,6,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
72,305,194340,06-Insulin (Non IV),9/4/2129 22:25,9/4/2129 22:26,4,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
73,305,194340,06-Insulin (Non IV),9/4/2129 17:00,9/4/2129 17:01,9,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
74,305,194340,06-Insulin (Non IV),9/4/2129 10:17,9/4/2129 10:18,8,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
75,305,194340,06-Insulin (Non IV),9/3/2129 22:00,9/3/2129 22:01,6,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,194340,305
76,305,194340,06-Insulin (Non IV),9/3/2129 16:21,9/3/2129 16:22,4,8/20/2129 18:03,9/7/2129 17:55,9/7/2129 17:55,1,101651,357
77,357,101651,06-Insulin (Non IV),10/21/2199 8:30,10/21/2199 8:31,4,10/20/2199 12:05,10/23/2199 17:30,NaN,0,101651,357
78,357,101651,06-Insulin (Non IV),10/20/2199 22:34,10/20/2199 22:35,20,10/20/2199 12:05,10/23/2199 17:30,NaN,0,117876,357
79,357,117876,06-Insulin (Non IV),12/28/2199 10:59,12/28/2199 11:00,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
80,357,117876,06-Insulin (Non IV),12/28/2199 10:59,12/28/2199 11:00,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
81,357,117876,06-Insulin (Non IV),12/27/2199 4:00,12/27/2199 4:01,2,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
82,357,117876,06-Insulin (Non IV),12/27/2199 23:00,12/27/2199 23:01,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
83,357,117876,06-Insulin (Non IV),12/27/2199 23:00,12/27/2199 23:01,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
84,357,117876,06-Insulin (Non IV),12/27/2199 16:17,12/27/2199 16:18,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
85,357,117876,06-Insulin (Non IV),12/27/2199 10:16,12/27/2199 10:17,2,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
86,357,117876,06-Insulin (Non IV),12/27/2199 10:16,12/27/2199 10:17,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
87,357,117876,06-Insulin (Non IV),12/26/2199 4:00,12/26/2199 4:01,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
88,357,117876,06-Insulin (Non IV),12/26/2199 22:00,12/26/2199 22:01,2,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
89,357,117876,06-Insulin (Non IV),12/26/2199 22:00,12/26/2199 22:01,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
90,357,117876,06-Insulin (Non IV),12/26/2199 16:00,12/26/2199 16:01,2,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
91,357,117876,06-Insulin (Non IV),12/26/2199 10:00,12/26/2199 10:01,6,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
92,357,117876,06-Insulin (Non IV),12/26/2199 10:00,12/26/2199 10:01,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
93,357,117876,06-Insulin (Non IV),12/25/2199 22:00,12/25/2199 22:01,6,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
94,357,117876,06-Insulin (Non IV),12/25/2199 22:00,12/25/2199 22:01,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
95,357,117876,06-Insulin (Non IV),12/25/2199 16:40,12/25/2199 16:41,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
96,357,117876,06-Insulin (Non IV),12/25/2199 10:00,12/25/2199 10:01,4,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
97,357,117876,06-Insulin (Non IV),12/25/2199 10:00,12/25/2199 10:01,60,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
98,357,117876,06-Insulin (Non IV),12/24/2199 22:45,12/24/2199 22:46,2,12/21/2199 22:37,1/18/2200 11:45,NaN,0,117876,357
99,357,117876,06-Insulin (Non IV),12/24/2199 22:45,12/24/2199 22:46,30,12/21/2199 22:37,1/18/2200 11:45,NaN,0,None,None